name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Tidy go.mod
        run: go mod tidy

      - name: Check diff
        run: git diff --exit-code

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Check diff
        run: git diff --exit-code
