name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    # teritorid hangs on ubuntu runner
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout teritori-dapp repo
        uses: actions/checkout@v4
        with:
          repository: TERITORI/teritori-dapp
          path: teritori-dapp
          ref: 66134e9580135a07aba64e00b68af9f30f8fdb93

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "teritori-dapp/yarn.lock"

      - name: Run integration tests
        run: make integration-tests
        env:
          TERITORI_DAPP_REPO: teritori-dapp
